### ISSUE TITLE
Windows user implementation

### ISSUE THREAD

**Issue by Changliu52** [bmegli/unity-network-hardware-video-decoder#14]
Thank you for sharing the project.
Understand the project was tested in linux 18.04. 
But since most unity users are in windows, so I was trying to run the project on windows 10, without luck.

Just wondering what needs to be changed in windows side? what challenge would it face in general?

**Comment by bmegli** [comment]
First make [HVD](https://github.com/bmegli/hardware-video-decoder) work
- the implementation is cross-platform
- I have no idea about the build system so you have to figure it out
- configure it for `dxva2` or `d3d11va` hardware acceleration
- make sure it works, it was never tested on Windows
- this is the most important part

The next step would be making [MLSP](https://github.com/bmegli/minimal-latency-streaming-protocol) work:
- the implementation is not cross-platform
- due to use of unix sockets
- so port it to winsock or use some cross-platform socket library
- the implementation has around 3 screens of code, this should be rather easy task for anybody who implemented native networking in windows before

Once you are past those 2 blockers put the bricks together (HVD + MLSP = NHVD), NHVD is used as plugin in UNHVD

There may be some boilerplate code to write to make NHVD work as dll for Unity (instead of so), I am not sure about that. 

Edits:
- corrected link to HVD

**Comment by bmegli** [comment]
The checkpoints would be:

1. Successfully initialize hardware for `dxva2` or `d3d11va` with HVD command line example.
2. After porting MLSP, build NHVD and successfully decode data with its command line examples.
3. Copy NHVD as plugin for UNHVD, configure it in Unity and successfully render incoming stream.

Feel free to reopen issue if you need more information.

**Comment by Changliu52** [comment]
I see. Thank you very much @bmegli

**Comment by FraDePace** [comment]
@Changliu52 Any updates regarding porting the project to Windows? :)
